version: '3.8'
services:
  backend:
    build:
      dockerfile: Dockerfile
    container_name: cm-backend
    stdin_open: true
    tty: true
    env_file: .env
    ports:
      - 8000:8000
    restart: always
    volumes:
      - .:/app
    networks:
      - app
  postgres:
    image: postgres:16.3-bookworm
    container_name: cm-postgres
    environment:
      POSTGRES_DB: "crypto-mind"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5432:5432"
    networks:
      - app
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: cm-pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: username@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - app
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:

networks:
  app:
    driver: bridge