"""Add binance accounts and trading bots tables

Revision ID: a9fd8f3c567e
Revises: d13bf61da37a
Create Date: 2024-12-29 04:00:21.439885

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9fd8f3c567e'
down_revision: Union[str, None] = 'd13bf61da37a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binance_account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('secret_key', sa.String(), nullable=False),
    sa.Column('account_type', sa.Enum('TESTNET', 'LIVE', name='binanceaccounttype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_binance_account_id'), 'binance_account', ['id'], unique=True)
    op.create_table('trading_bot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('binance_account_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tickers', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['binance_account_id'], ['binance_account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_bot_id'), 'trading_bot', ['id'], unique=True)
    op.create_table('bot_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['trading_bot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_activity_id'), 'bot_activity', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_activity_id'), table_name='bot_activity')
    op.drop_table('bot_activity')
    op.drop_index(op.f('ix_trading_bot_id'), table_name='trading_bot')
    op.drop_table('trading_bot')
    op.drop_index(op.f('ix_binance_account_id'), table_name='binance_account')
    op.drop_table('binance_account')
    # ### end Alembic commands ###
