name: Build and deploy Python app to Azure Web App (Container)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write #This is required for requesting the JWT
  contents: read

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure ACR Login
        run: az acr login --name ${{ secrets.ACR_NAME }} --username ${{ secrets.ACR_NAME }} --password ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_image
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Configure the Azure Web App to use the container image from ACR
      # Replace <YourResourceGroup> and 'crypto-mind-backend' with your actual resource group and app name
      - name: Configure Web App to use the container
        run: |
          az webapp config container set \
            --name crypto-mind-backend2 \
            --resource-group crypto-mind-rg \
            --container-image-name ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:latest \
            --container-registry-url https://${{ secrets.ACR_NAME }}.azurecr.io \
            --container-registry-user ${{ secrets.ACR_NAME }} \
            --container-registry-password ${{ secrets.ACR_PASSWORD }}